-- 1) links: 유튜브 링크 단위 "여행 계획"
create table if not exists public.links (
  id bigint generated by default as identity primary key,

  -- 계획 제목 (AI 생성 + 사용자 수정)
  title_ai text,
  title_user text,

  -- 유튜브 메타
  youtube_url text not null,
  youtube_video_id text,
  youtube_channel_name text,
  youtube_channel_id text,

  -- ===== Realtime용 추출 상태 =====
  -- 서비스 레이어에서 값 관리:
  -- status: PENDING | PROCESSING | READY | FAILED
  status text not null default 'PENDING',
  progress_pct int not null default 0,   -- 0~100 (검증은 서비스 레이어)
  stage text,                            -- 예: fetch_meta/extract_places/persist
  status_message text,                   -- UI에 보여줄 한 줄 상태

  -- 실패 정보 (FAILED일 때 채우기)
  error_code text,                       -- 예: YT_FETCH_FAILED, TRANSCRIBE_TIMEOUT 등
  error_message text,                    -- 사용자/디버깅용 메시지
  error_detail jsonb,                    -- 원본 에러 payload (선택)

  -- 타임스탬프
  started_at timestamptz,
  finished_at timestamptz,
  parsed_at timestamptz,                 -- 성공 시 완료 시각(READY)
  heartbeat_at timestamptz,              -- 워커 생존 체크(선택)

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists links_created_at_idx on public.links (created_at desc);
create index if not exists links_video_id_idx on public.links (youtube_video_id);
create index if not exists links_status_idx on public.links (status);


-- 2) link_place_items: 영상에 나오는 개별 장소
create table if not exists public.link_place_items (
  id bigint generated by default as identity primary key,
  link_id bigint not null references public.links(id) on delete cascade,

  place_name text not null,

  -- 서비스 레이어에서 값 관리:
  -- category: TNA | LODGING
  category text,

  -- 타임라인(초 단위 권장)
  timeline_start_sec int,
  timeline_end_sec int,

  country text,
  city text,

  youtuber_comment text,
  user_memo text,

  order_index int,                       -- UI 순서(검증/중복 방지 등은 서비스 레이어)
  is_deleted boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lpi_link_id_idx on public.link_place_items (link_id);
create index if not exists lpi_link_order_idx on public.link_place_items (link_id, order_index);
create index if not exists lpi_link_active_idx on public.link_place_items (link_id) where is_deleted = false;


-- 3) updated_at 자동 갱신 트리거
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_links_updated_at on public.links;
create trigger set_links_updated_at
before update on public.links
for each row execute function public.set_updated_at();

drop trigger if exists set_lpi_updated_at on public.link_place_items;
create trigger set_lpi_updated_at
before update on public.link_place_items
for each row execute function public.set_updated_at();


-- 4) Realtime 활성화 (상태 변경 실시간 구독용)
alter publication supabase_realtime add table public.links;

